apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:0.11.0
        ports:
        # exposing dynamodb
        - containerPort: 31001
        # exposing sqs
        - containerPort: 31000
        # exposing s3
        - containerPort: 31002  
        # exposing iam
        - containerPort: 31003
        # expsosing the localstack ui
        - containerPort: 32000
        env:
          - name: SERVICES
            value: "sqs:31000,dynamodb:31001,s3:31002,iam:31003"
          - name: PORT_WEB_UI
            value: "32000"
---

apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  # selector tells Kubernetes what Deployment this Service
  # belongs to
  selector:
    app: localstack
  ports:
  - port: 32000
    protocol: TCP
    name: ui
    nodePort: 32000

  - port: 31001
    protocol: TCP
    name: dynamodb
    nodePort: 31001

  - port: 31000
    protocol: TCP
    name: sqs
    nodePort: 31000

  - port: 31002
    protocol: TCP
    name: s3
    nodePort: 31002

  - port: 31003
    protocol: TCP
    name: iam
    nodePort: 31003

  type: NodePort

